0) Enable profiling of Ezhil code. 1) Add tracebacks where necessary. 2) Add unittest and examples for profiling -gcd, fact, profile_test.py 3) Refactor the env behavior with runtime 4) test sentinel fixup to run goldenratio.n and array_wr.n 5) accept parameter called stacksize to Ezhil CLI 6) make exprs code to return a 255 exit code upon exception 7) make unittests for failing exprs code to run fast and less verbose 8) exprs code fails properly now
10) Add profiling information to any program on the fly; '-profile'
11) add entry/exit calls to profile("begin") and profile("results") as we go.
12) API update to raw_input to be i/p exception safe to Interpreter state
13) Handle exceptions better during raw_input calls
14) add capability to  QuietTest unittest class
15) update hello.n to not break the prettyprinter test
16) HTML API update

21) Mathematics series + sequence operations for Ezhil programs
22) Ezhil Interpreter - ezhili
23) update test script

31) Add ezhil test for interactive programs using echo
32) simple demos
33) enable the programs stored in Tamil/unicode file names to be executed correctly
34) file_close failed due to serializing env - we wont attemp this from now on
35) hanoi.n - dont mix str and unicode
36) test - recover the filerw.n as well
37) down to 15 failures
38) update str.x methods to string.x which are encoding compatible;

40) unittest for running Python2 and 3 versions
41) Python3 recognizes Ezhil code; we are at starting line.
42) Code can be optimistically ported between 2-3
43) improve profiling output formatting;
44) update yinyang to skip the pause
45) input stream should not be opened in UTF-8 for Python2 nor Python3
46) dump_file is the name we use within tests
48) Fix call-stack and local scoped variable unwinding of interpreter if any exceptions were thrown.
49) This resolves issue #60. "After runtime error local variables are trashed; #60"
50) Python3 testing for Ezhil; unittest3 is not ready;
51) fixup the unittest and error stack during the file execution

51) make profiling work in Python3
52) update list/dictionary key/value retval in Python2/3 barriers
53) update test3 sentinel to use suffix 3 log files during test.

61) failures only in Python3

diff --git a/test b/test
--- a/test
+++ b/test
@@ -48,11 +48,19 @@ change.n solo_return.n listmt.n predicates.n sexpr.n dict_ta.n \
 fruity.n optional.n sine_qua_non.n armstrong.n array0.n array_nd.n \
 tamil_letters.n tamil_months.n tower_of_hanoi.n hanoi.n \
 max_wo_compare.n powers_of_two.n sum_of_digits.n bmi.n isbalanced.n mangalyaan.n \
-boolf.n globalvars.n tamil1.n tamil2.n tamil_tha.n \ 
+boolf.n globalvars.n tamil1.n tamil2.n tamil_tha.n \
+ta_strings.n \
 array_wr.n \
+math_arithprogression.n \
+math_geomprogression.n \
+math_harmonicseries.n \
+math_complex.n \
+math_goldenratio.n \
+math_horner.n \
 dict_rw.n \
+ml.n \
 beer_bottles_song.n \
-golden_ratio \
+sort.n \
 bitwiseops.n \
 mathipeedu.n \
 staircase_light.n \
@@ -61,6 +69,9 @@ boolean_demorgan.n \
 nonexistent_file.n \
 half_adder.n \
 full_adder.n \
+eval0.n \
+eval1.n \
+ta_sort.n \
 neuron.n varavu_selavu.n calc2.n name_var.n py1.n demoif.n morse.n partition_estimate.n | sort`
 do
     echo "########## Testing Ezhil script $i $1" | tee -a ../dump_file    
@@ -104,13 +115,27 @@ else
 fi
 
 echo "**************************************************"
+echo " Running interactive tests " | tee -a dump_file
+echo "***************************************************"
+for i in `echo demos/ch2.n \
+`
+do
+    echo "ezhil" | python ./ezhil/ezhil.py ./tests/$i  >>  dump_file
+    if [ $? -eq 0 ]
+    then
+	echo "passed ezhil interactive test for  $i" >> success.txt
+    else
+	echo "failed ezhil interactive test for $i" >> failed.txt
+    fi
+done
+
+echo "**************************************************"
 echo " Running all the failure programs, that must fail."
 echo "**************************************************"
-sleep 2
 for i in `ls ./tests/*.fprog`;
 do
     echo "Testing file $i" | tee -a dump_file
-    python ./ezhil/exprs.py $i $1 2>&1 >> dump_file
+    python ./ezhil/exprs.py $i $1 -stacksize 10 2>&1 >> dump_file
     if [ $? -eq 0 ]
     then
 	echo $i >> failed.txt
@@ -137,19 +162,13 @@ echo "Passed = "`wc -l success.txt`", Failed = "`wc -l failed.txt`
 # ./tests/exprs/condtest.prog
 # ./tests/exprs/dim2d_array.prog
 # ./tests/exprs/ifelseif.prog
-# gigo.n
 # badlex.n
 # temple.n
-# கூட்டு.n
-# strings.n
-# string_demo.n
-# split_text.n
 # solo_return.n
-# hanoi.n
 # boolf.n
 # nonexistent_file.n
-
-NFAIL=16 #11/15/15
+# eval1.n
+NFAIL=12 #11/18/15
 TOTFAIL=`wc -l failed.txt | cut -d'f' -f1`
 echo "from sys import exit; ( $TOTFAIL <=  $NFAIL ) and exit(0) or exit(255)" | python
 if [ $?  -eq 0 ]
@@ -159,10 +178,10 @@ then
 else
    echo "Expecting $NFAIL failures, but found $TOTFAIL failures" | tee -a dump_file
    echo "Too few/many failures; some negative tests may have failed" | tee -a dump_file
-   echo "" | tee -a dumpfile
+   echo "" | tee -a dump_file
    echo "######### LIST OF FAILED FILES ##############" | tee -a dump_file
-   cat failed.txt | tee -a dumpfile
-   echo " " | tee -a dumpfile
+   cat failed.txt | tee -a dump_file
+   echo " " | tee -a dump_file
    exitcode=255 #failed failures != $NFAIL
    exit $exitcode
 fi
